### ISSUE TITLE
PULL_REQUEST_TEMPLATE.md is needed?

### ISSUE THREAD

**Issue by nekketsuuu** [Drassil/git-wiki#2]
Being different from Drassil/git-wiki-theme, pull requests to this repository usually update wiki articles instead of bug fixes or feature requests. So [PULL_REQUEST_TEMPLATE.md](https://github.com/Drassil/git-wiki/blob/e508940b2aa8e53e2b6fd1b26afc6c3f731714f2/PULL_REQUEST_TEMPLATE.md) may be unnecessary. At least its content such as "How Has This Been Tested?" is unnecessary.

How about removing the file like ISSUE_TEMPLATE?

**Comment by Yehonal** [comment]
We should not delete that file since can be used for wiki contributions

https://github.com/Drassil/git-wiki/commit/53875b8bb2bd11610ad57043d5a4a1258600b6d2
