### ISSUE TITLE
jekyll build issue under jekyll v3.7.2

### ISSUE THREAD

**Issue by overheat** [Drassil/git-wiki#20]
Hi,

I can use "jekyll build" and "jekyll serve" to check the result locally on my PC.
But I only see a folder tree, when I try git-wiki, like this:
http://127.0.0.1:4000/
`

Name | Last modified | Size
-- | -- | --
Parent Directory | 2018/02/16 23:10 | -
404.html | 2018/02/16 23:11 | 2816
LICENSE | 2018/02/16 21:57 | 1078
assets/ | 2018/02/16 23:10 | -
feed.xml | 2018/02/16 23:11 | 486
index.md | 2018/02/16 22:01 | 12
redirects.json | 2018/02/16 23:11 | 2
robots.txt | 2018/02/16 23:11 | 43
sitemap.xml | 2018/02/16 23:11 | 285
sync-wiki.sh | 2018/02/16 21:57 | 244

`

**Comment by overheat** [comment]
The log is:
`:~/workspace/git-wiki$ jekyll serve --no-watch
Configuration file: /mnt/c/Users/aaron/Desktop/workspace/git-wiki/_config.yml
            Source: /mnt/c/Users/aaron/Desktop/workspace/git-wiki
       Destination: /mnt/c/Users/aaron/Desktop/workspace/git-wiki/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
    Liquid Warning: Liquid syntax error (line 56): Unexpected character { in "{{{page.folder}}" in /_layouts/default.html
    Liquid Warning: Liquid syntax error (line 57): Unexpected character { in "{{{page.folder}}" in /_layouts/default.html
    Liquid Warning: Liquid syntax error (line 58): Unexpected character { in "{{{page.folder}}" in /_layouts/default.html
    Liquid Warning: Liquid syntax error (line 60): Unexpected character { in "{{{page.folder}}" in /_layouts/default.html
    Liquid Warning: Liquid syntax error (line 62): Unexpected character { in "{{{page.folder}}" in /_layouts/default.html
    Liquid Warning: Liquid syntax error (line 64): Unexpected character { in "{{{page.folder}}" in /_layouts/default.html
    Liquid Warning: Liquid syntax error (line 65): Unexpected character { in "{{{page.folder}}" in /_layouts/default.html
                    done in 0.558 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
    Server address: http://127.0.0.1:4000
  Server running... press ctrl-c to stop.`

**Comment by overheat** [comment]
> :~/workspace/git-wiki$ jekyll serve --no-watch
Configuration file: /mnt/c/Users/aaron/Desktop/workspace/git-wiki/_config.yml
            Source: /mnt/c/Users/aaron/Desktop/workspace/git-wiki
       Destination: /mnt/c/Users/aaron/Desktop/workspace/git-wiki/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
    Liquid Warning: Liquid syntax error (line 56): Unexpected character { in "{{{page.folder}}" in /_layouts/default.html
    Liquid Warning: Liquid syntax error (line 57): Unexpected character { in "{{{page.folder}}" in /_layouts/default.html
    Liquid Warning: Liquid syntax error (line 58): Unexpected character { in "{{{page.folder}}" in /_layouts/default.html
    Liquid Warning: Liquid syntax error (line 60): Unexpected character { in "{{{page.folder}}" in /_layouts/default.html
    Liquid Warning: Liquid syntax error (line 62): Unexpected character { in "{{{page.folder}}" in /_layouts/default.html
    Liquid Warning: Liquid syntax error (line 64): Unexpected character { in "{{{page.folder}}" in /_layouts/default.html
    Liquid Warning: Liquid syntax error (line 65): Unexpected character { in "{{{page.folder}}" in /_layouts/default.html
                    done in 0.558 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
    Server address: http://127.0.0.1:4000
  Server running... press ctrl-c to stop.

**Comment by overheat** [comment]
The log is:

> :~/workspace/git-wiki$ jekyll serve --no-watch
Configuration file: /mnt/c/Users/aaron/Desktop/workspace/git-wiki/_config.yml
            Source: /mnt/c/Users/aaron/Desktop/workspace/git-wiki
       Destination: /mnt/c/Users/aaron/Desktop/workspace/git-wiki/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
    Liquid Warning: Liquid syntax error (line 56): Unexpected character { in "{{{page.folder}}" in /_layouts/default.html
    Liquid Warning: Liquid syntax error (line 57): Unexpected character { in "{{{page.folder}}" in /_layouts/default.html
    Liquid Warning: Liquid syntax error (line 58): Unexpected character { in "{{{page.folder}}" in /_layouts/default.html
    Liquid Warning: Liquid syntax error (line 60): Unexpected character { in "{{{page.folder}}" in /_layouts/default.html
    Liquid Warning: Liquid syntax error (line 62): Unexpected character { in "{{{page.folder}}" in /_layouts/default.html
    Liquid Warning: Liquid syntax error (line 64): Unexpected character { in "{{{page.folder}}" in /_layouts/default.html
    Liquid Warning: Liquid syntax error (line 65): Unexpected character { in "{{{page.folder}}" in /_layouts/default.html
                    done in 0.558 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
    Server address: http://127.0.0.1:4000
  Server running... press ctrl-c to stop.

**Comment by Yehonal** [comment]
This wiki is intended to work with github pages that uses jekyll 3.6.2

I never tried to build it locally

Il 17 Feb 2018 01:11, "Aaron Tsui" <notifications@github.com> ha scritto:

**Comment by kpfleming** [comment]
There is a syntax error in all of these locations, and the newer version of Liquid catches it. There are three '{' in a row, when there should only be two. With this changed, Jekyll 3.7.2 has no problem with this theme.

**Comment by nok-ko** [comment]
@kpfleming Having fixed the syntax errors, the theme still refuses to serve properly on my machine under Jekyll 3.7.3

**Comment by kpfleming** [comment]
Odd. It's working for me with 3.7.2, haven't had a chance to upgrade to 3.7.3 yet.

**Comment by sourabhdeshmukh** [comment]
@Yehonal Can you please provide README.md for this repository for Installing or hosting theme locally.

**Comment by Yehonal** [comment]
@kpfleming could you open a PR to fix that syntax issue please?

@sourabhdeshmukh sorry but i don't use it for local installations so i can't write such guide. But please feel free to open a PR to improve the README if you are able to write a guide for it.
