### ISSUE TITLE
I just wanted to offer to add my wiki to the examples page

### ISSUE THREAD

**Issue by anoduck** [Drassil/git-wiki#21]
I am tying to keep an opinionated wiki of the things I learn and have learned over the years. You are more than welcome to add it to the examples page if so desired.

https://anoduck.github.io/wiki/

**Comment by Yehonal** [comment]
Hi! Sure thing! Can you please create a PR for it?

**Comment by anoduck** [comment]
@Yehonal OK, sure thing, I should have known to do that. My completion system is being repaired in Emacs at the moment, but I will get that done superfast afterward.

**Comment by anoduck** [comment]
@Yehonal Where does the favicon get loaded from? Is it directly in the repo root, in the assets folder?
