### ISSUE TITLE
Clarification Needed: Why Specify `wiki_folder` and what are the implications?

### ISSUE THREAD

**Issue by chaojian-zhang** [Drassil/git-wiki#24]
Hi, thanks for the great template! Works like a charm. This is not an issue with the theme but more like a documentation clarification.

In the config file there is this line:

```yaml
# (string) folder where wiki pages are stored, it's needed for tool buttons
wiki_folder: "wiki"
```

I wonder what does **"tool buttons"** refer to? Is this referring to the download buttons from the sidebar?

On the other hand, if I put entries inside folders other than the specified `wiki_folder`, they can render fine and even Edit buttons work fine on those files - so I wonder why is it necessary to specify `wiki_folder` and what are the implications to the files that's put outside those folders?

For instance, from the [basic skeleton](https://github.com/Drassil/git-wiki-skeleton), it's apparent the _posts are not placed inside wiki folder - what does it mean?

**Comment by Yehonal** [comment]
This is needed for the "Add new page" button. 

However, please use the right report for the issues next time: https://github.com/Drassil/git-wiki/issues/12

Thank you
