### ISSUE TITLE
Edit tools do not link correctly to index.md if address is a subdirectory.

### ISSUE THREAD

**Issue by nichdel** [Drassil/git-wiki#6]
Hello, and thanks for your work on this! My community is trying it as a solution to our wiki needs.

Steps to reproduce:

1. Create a subdirectory.
2. Create an index.md
3. Navigate to projecturl/wiki/subdirectory
4. Press either edit option.

An example can be seen [here](http://agora.matchapunk.com/wiki/Assessor/).

**Comment by Yehonal** [comment]
Hi! thank you!

I've fixed it in latest commits. 

Please sync your fork

**Comment by Yehonal** [comment]
Also, please consider to add your wiki to our showreel if you want: 
http://www.drassil.org/git-wiki/wiki/Showreel.html
